
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 1.0], ["minecraft:the_end", -0.1]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["minecraft:soul_sand_valley", 53, 53, "F"], ["minecraft:old_growth_birch_forest", 58, 72, "F"], ["minecraft:river", 60, 70, "F"], ["minecraft:swamp", 72, 84, "F"], ["minecraft:savanna", 70, 95, "F"], ["minecraft:savanna_plateau", 76, 98, "F"], ["minecraft:windswept_savanna", 67, 90, "F"], ["minecraft:taiga", 44, 62, "F"], ["minecraft:snowy_taiga", 19, 48, "F"], ["minecraft:old_growth_pine_taiga", 48, 62, "F"], ["minecraft:old_growth_spruce_taiga", 48, 62, "F"], ["minecraft:desert", 48, 115, "F"], ["minecraft:stony_shore", 50, 64, "F"], ["minecraft:snowy_beach", 38, 52, "F"], ["minecraft:snowy_slopes", 24, 38, "F"], ["minecraft:windswept_forest", 48, 66, "F"], ["minecraft:frozen_peaks", 15, 33, "F"], ["minecraft:warm_ocean", 67, 76, "F"], ["minecraft:deep_frozen_ocean", 56, 65, "F"], ["minecraft:jungle", 76, 87, "F"], ["minecraft:bamboo_jungle", 76, 87, "F"], ["minecraft:badlands", 84, 120, "F"], ["minecraft:wooded_badlands", 80, 108, "F"], ["minecraft:eroded_badlands", 88, 120, "F"], ["minecraft:deep_dark", 63, 63, "F"]]

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: The temperature of the block, in Minecraft units
	#*falloff: The block is less effective as distance increases
	#*max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	#*predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	#- (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	#*nbt: The NBT data that the block must have for the temperature to be applied.
	#*temperature-limit: The maximum world temperature at which this block temp will be effective.
	#- (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, 0.88, "frosted=true", "", 0], ["minecraft:fire", 0.476, 7, 0.9, "", "", 8], ["#minecraft:campfires", 0.476, 7, 0.9, "lit=true", " ", 8], ["minecraft:magma_block", 0.25, 3, 1.0], ["minecraft:lava_cauldron", 0.5, 7, 1.5], ["#minecraft:ice", -0.15, 4, 0.6, "", "", -0.7], ["minecraft:ice", -0.15, 4, 0.6, "", "{}", -0.7], ["minecraft:packed_ice", -0.25, 4, 1.0, "", "{}", -0.7], ["minecraft:blue_ice", -0.35, 4, 1.4, "", "{}", -0.7]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = true
	#When set to true, modifies ice blocks to be harvestable with a pickaxe
	"Custom Ice Drops" = true

[Misc]
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = []
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

[Hearth]
	#Allows the hearth to automatically turn on/off based on nearby players' temperature
	#If false, the hearth turns on/off by redstone signal
	"Automatic Hearth" = false
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.75
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "#minecraft:leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

